import json

from prompt.prompt import Prompt


class Tests(Prompt):
    path = "../data/tests.json"

    def __init__(self, idx, data, lang="java"):
        self.idx = idx
        self.data = data
        self.lang = lang
        # Load Prompts
        with open(self.path) as file:
            self.prompt = json.loads(file.read())

    def parse_response(self, prompt_idx, response):
        # Idea here is to check the response from GPT and make sure it makes sense, else give additional prompts
        # to get the correct response.

        if len(self.prompt) <= prompt_idx:
            return False
        # Returns True if prompt is parsed else False, give additional prompts if False
        return True

    def store(self, idx, out):
        # Writing to a file based on the language passed in the command line
        with open("output/markdowns/" + str(idx) + ".md", "w") as file:
            file.write("\n\n".join(out))

    def write_unit_test(self, idx, message):
        # Writing the unit test generated by GPT into a new file
        start = "<JunitTest>"
        end = "</JunitTest>"
        print(f'[TEST] message: {message}')
        code = message[message.index(start) + len(start): message.index(end)]
        print(f'[TEST] code: {code}')
        with open("output/generated-tests/" + str(idx) + ".java", "w") as file:
            file.write(code)
